server:
    port: 9002
spring:
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

oss:
  pathDirectory: /upload/
  ossRecordPath: /upload/record.log

  ossServerUrl: http://localhost:9002/fileService/uploadFile2
  deleteServerUrl : http://localhost:9002/fileService/delete

  token : 38x3123dc35r5

